### ISSUE TITLE
FR: About Delay plugins at start, it could be  delaying the start of plugins at boot every time.

### ISSUE THREAD

**Issue by YIRU69** [1C0D/obsidian-quick-plugin-switcher#16]
The https://github.com/Mocca101/obsidian-plugin-groups plugin  shown a serious bug in version 1.5.7.

I am concerned that the author no longer maintains it, and I also recommend the obsidian-quick-plugin-switcher plugin. https://github.com/Mocca101/obsidian-plugin-groups/issues/41

I have carefully read your documentation and there is indeed a "Delay plugins at start" feature, but from my testing, it seems it can only maintain a reboot once?If so, could the author please merge the functionality of obsidian-plugin-groups, which is about delaying the start of plugins at boot. The purpose of doing this is to speed up the start-up time of opening obsidian.

Welcome to communicate with the author if you have any ideas, and thank you again for your contribution.

**Comment by 1C0D** [comment]
version ?
Maybe I introduced a bug with my last modificiation. Because platform dependant start and delay at start are linked.

**Comment by 1C0D** [comment]
Version 6.0.0
ok I introduced a bug. 
Will see this

**Comment by YIRU69** [comment]
Hi, It not work on the verison 6.0.2.

**Comment by YIRU69** [comment]
@1C0D 
If I have any operational issues, please remind me. This is how I operate: 
1. Double-click the left mouse button to set the time, then manually close the plugin, and then restart Obsidian. 
2. Double-click the left mouse button to set the time, then do not close the plugin, and then restart Obsidian. I found that the plugin does not start with a delay in either of these two ways.

**Comment by 1C0D** [comment]
https://github.com/1C0D/obsidian-quick-plugin-switcher/assets/63018905/18a9073c-2740-404c-95b5-b296a194d7ce

**Comment by YIRU69** [comment]
Thank you so much. It works.
