### ISSUE TITLE
FR: Add a pinning feature for plugins.

### ISSUE THREAD

**Issue by YIRU69** [1C0D/obsidian-quick-plugin-switcher#17]
Now, this plugin is one of many I use frequently, and I want to make it more user-friendly, hence I'm suggesting an improvement based on my workflow, hoping the author may consider this.

As the title suggests, I propose to add a pinning feature whose purpose it to place commonly used plugins at the top of the plugin list. I previously mentioned a similar feature, of the cursor automatically focusing on the input box when entering a plugin, but I now feel I may not have fully considered that suggestion. Why not simply place my frequently used plugins directly at the top?

**Comment by 1C0D** [comment]
it's difficult to add anything above the input as a pinning icon. Because it's considered as text. Else where this is no more place.
Why don't you plugins to a group ? that's the main goal of groups ^^

**Comment by YIRU69** [comment]
I have used groups, but even after adding them, extra steps are needed. If you can add a memory function to the button at the top right, I think it would be better. What I mean is if I switch to "By group," then next time I open Obsidian or the plugins, it remains on "By group."

**Comment by 1C0D** [comment]
I will see if I can add an option in settings to keep the same dropdown entry on restart. but it was a difficult part to code. BTW I have a lot of important issue to solve on other plugins, so it will take time. But I will consider this

**Comment by 1C0D** [comment]
good news, it was not so difficult, so I added a new setting, turn on by defaut, to keep the last value of dropdowns after a reload/reopen of each modal. So you can indeed access faster to a group

**Comment by 1C0D** [comment]
good news, it was not so difficult, so I added a new setting, turn on by defaut, to keep the last value of dropdowns after a reload/reopen of each modal. So you can indeed access faster to a group

**Comment by YIRU69** [comment]
It works. Thank you!
