### ISSUE TITLE
FR: Add reload plugin button

### ISSUE THREAD

**Issue by LostPaul** [1C0D/obsidian-quick-plugin-switcher#18]
I would be nice to be able to reload a plugin through the model of this plugin. This plugin should help you implement the function: https://github.com/Benature/obsidian-plugin-reloader

**Comment by 1C0D** [comment]
this code is simply disabling enabling a plugin you can do it quickly trough the toggle button. if it is for development you can use hot reload, cumulated to reload without saving command. and if not, my plugin is going through a more complex process, cumulated enable and save and just enable when it's a delayed plugin and something similar when it's platform dependent. Meaning you can share a vault and have some plugins enabled or not on mobile or desktop. 
I don't see why he is reloading all plugins. hot reload use a file that you can create to only reload the plugin you want.

**Comment by 1C0D** [comment]
I added a functionality to add a command to a plugin (context menu) and if you run this command it will toggle the plugin (enabled/disabled)

**Comment by LostPaul** [comment]
Alright that's great thanks but an explanation somewhere would be great or a name that makes it more obvious for others to know what it is for.

**Comment by 1C0D** [comment]
I explain it in the readme with this gif. If you think about another command name, let me know.
