### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by JoKo1959** [1C0D/obsidian-quick-plugin-switcher#19]
This is a very useful plugin; thank you for developing it!
I use Obsidian on several machines and synchronize with the Obsidian sync service. This also synchronizes the settings of the community plugins. However, sync of the specific settings (like names of the groups...) does not work for the Quick-Plugin-Switcher. Is there any help for this?

**Comment by 1C0D** [comment]
I asked on the dev forum and got this answer:

ClareMacrae
 — 
Aujourd’hui à 16:34
It's easy.
On Machine 1, save settings.
Changes get synced to Machine 2.

Obsidian is not restarted on Machine 2, so your plugin is still running with the settings pre sync.

User changes settings on Machine 2. Settings from Machine 1 still not present.
Settings get synced back to Machine 1.

Next time Obsidian is restarted on Machine 1, it has only the settings edits on Machine 2.

and this:
It's an undocumented behaviour of Obsidian Sync that if you change plugin settings on any one machine, after sync, you should restart all the other instances of the vault on other machines, before making settings changes on any of those other machines.
(That noise in the distance is people who are fed up of me pointing this out repeatedly... I've got a snippet saved to share that 'Sync is hard' link now...)

I had a similar behavior syncing with dropbox if I let obsidian opened before to sync (it was creating a conflicting-data.json ( data.json is where settings are saved)

tell me if it solving your problem. the conversation can be found there https://discord.com/channels/
686053708261228577/840286264964022302/1213509857915707442

**Comment by 1C0D** [comment]
this seems useful 
Tip: To find when conflicts have happened, you can search for "Merging conflicted file" in Settings → Sync → Sync activity → View. there https://github.com/obsidianmd/obsidian-help/pull/197

**Comment by JoKo1959** [comment]
Thank you very much for your support. But the problem has not been solved. I am working on two Windows machines. If I change the settings for the plugin on machine 1, then synchronize and only then start Obsidian on machine 2 and wait until Obsidian is also synchronized on machine 2, the changes in the plugin from machine 1 are still not applied to machine 2.

**Comment by 1C0D** [comment]
For the moment, I'm clueless. 
Just few checks to be sure:
- Most recent version of QPS
- You can delete the data.json (in this order: you open the quick switcher plugin folder, close all instances of obsidian for this vault, delete the data.json (you can do a copy). So now all settings have been reset, is there still a problem? (of course you can do a fresh installation of QPS too, but this is the same result). 
- I don't think some other plugin could interfere, but you can disable all other plugin (there is a button in QPS for this). And see if changes.

**Comment by 1C0D** [comment]
ok someone has written some code linked to this. I will try to implement it to see if you have no issue anymore.

**Comment by 1C0D** [comment]
(for my own reference https://github.com/javalent/calendarium/blob/c97948a4966c88b6fdd520995a52b258380ef5f6/src/settings/settings.service.ts#L120-L182)

**Comment by 1C0D** [comment]
version 7.4.1
I reviewed save settings. Is there any change ?

**Comment by JoKo1959** [comment]
Thank you for your efforts. I have installed the plugin update on both machines; the Obsidian version is also up to date. I have made changes to the plugin on machine 1. The json file is displayed in the sync log and synchronized on machine 1. Only then do I start Obsidian on machine 2, where the json file also appears in the sync log and is correctly synchronized. However, the changes to the plugin on machine 1 are not transferred to machine 2.
Can perhaps another user replicate the behavior?
Thank you

Von: 1C0D ***@***.***>
Gesendet: Dienstag, 5. März 2024 15:50
An: 1C0D/obsidian-quick-plugin-switcher ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [1C0D/obsidian-quick-plugin-switcher] Sync (Issue #19)


version 7.4.1
I reviewed save settings. Is there any change ?

**Comment by 1C0D** [comment]
So it corrected something ? 
At this point, I don't think this is linked to the plugin, or I don't understand why its happening at the moment.  But anyway it would be great to ask more info on the forum as bug linked to sync or see on the discord. I will to reach a dev at first on discord

**Comment by 1C0D** [comment]
version 7.5.0
fixed !
It was so simple to explain that I wonder why it took 3 days on the dev server. A method is existing, in the obsidian API, and you just have to implement it in your code at the right place, without calling it (autocalled), and that's all folks.

**Comment by JoKo1959** [comment]
Great! Now it is working perfectly. Thanks a lot

Von: 1C0D ***@***.***>
Gesendet: Dienstag, 5. März 2024 19:33
An: 1C0D/obsidian-quick-plugin-switcher ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [1C0D/obsidian-quick-plugin-switcher] Sync (Issue #19)


version 7.5.0
fixed !
It was so simple to explain that I wonder why it took 3 days on the dev server. A method is existing, in the obsidian API, and you just have to implement it in your code at the right place, without calling it (autocalled), and that's all folks.
