### ISSUE TITLE
How to add delay?

### ISSUE THREAD

**Issue by Asetnozama** [1C0D/obsidian-quick-plugin-switcher#21]
Can someone please explain me how to add a delay on startup for a plugin?
Double click doesn't do anything....

Thanks

**Comment by 1C0D** [comment]
this is a bug I introduced. I will check this

**Comment by 1C0D** [comment]
Done (version 8.0.1)
Thanks for having reported. it was a bug introduced in recent version.
You can double click again. Same to delete the delay. 
And you can add several delays via group too: add group, right click on group in group bar and add delay to group. to remove do it again, setting delay to 0 or nothing

**Comment by Asetnozama** [comment]
Thank you very much!
