### ISSUE TITLE
Ability to add one plugin to multiple groups

### ISSUE THREAD

**Issue by TonyAtlas** [1C0D/obsidian-quick-plugin-switcher#3]
I think there may be situations when one plugin can be assigned to two or more groups at once.

If it is technically possible, it would add freedom in plugin management.

**Comment by 1C0D** [comment]
in progress
![image](https://github.com/1C0D/obsidian-quick-plugin-switcher/assets/63018905/3045149d-db92-483f-8bc9-67ddb3ecdd23)
