### ISSUE TITLE
Failure to Update/re·Install with Latest

### ISSUE THREAD

**Issue by lwb52** [1C0D/obsidian-quick-plugin-switcher#5]
today, 9/13/23, not updating – & failing to reinstall after deletion – on latest insider builds in both M1-iOS16.6.1 & M2-OSx13.5.2

**Comment by arthurwerry** [comment]
Ditto.  After uninstalling I cannot get a reinstall.  Even with a manual copying into my vault, fails when trying to enable it.

**Comment by 1C0D** [comment]
Can you confirm the last update is ok

**Comment by arthurwerry** [comment]
Yes!   Thank you so much!

**Comment by lwb52** [comment]
thank you!!Sent from PadProOn Sep 30, 2023, at 3:36 PM, 1C0D ***@***.***> wrote:﻿
Closed #5 as completed.
