### ISSUE TITLE
Can't type 'i' or another 'hotkey' into the search bar without triggering the hotkey - makes search unusable

### ISSUE THREAD

**Issue by daniel347x** [1C0D/obsidian-quick-plugin-switcher#6]
Greetings, and thanks for the plugin.

Whenever I try to filter to show only a certain plugin by typing its name into the Search bar, I find that if the name of the plugin starts with one of the hotkeys:

- f
- g
- i
- s
- h

...corresponding to the 'Quick Plugin Switcher' hotkeys, then the hotkey action is triggered in addition to the character appearing in the Search box.

Here is a screenshot:

![image](https://github.com/1C0D/obsidian-quick-plugin-switcher/assets/309746/c935ce97-d32d-4235-9a17-451e3f6a0978)

...Any way to update the plugin so that if a hotkey is typed, but the Search bar is active, that the hotkey is ignored so that the user can type any character into the Search bar?

Thanks so much again!

**Comment by 1C0D** [comment]
I will have a look at this

**Comment by 1C0D** [comment]
is it fixed for you?

**Comment by 1C0D** [comment]
I can't reproduce. is it fixed?

**Comment by daniel347x** [comment]
Thanks for looking at this.

Sadly, no, the issue persists.

It must be some conflict with another plugin installed, or something like that.

Unfortunately, I do not have time right now to track it down.

However, there is an easy workaround that I use:

- I just hit the CAPS LOCK key prior to typing in the search box. Fortunately, this works as the search is not case-sensitive.

I just have to remember to turn off CAPS LOCK when I'm done.

This is a super helpful plugin and I use it all the time.

Thanks!

**Comment by 1C0D** [comment]
at list now i will be ctrl. I cleaned better main listeners so there is less key repetitions. they were cumulating. they are many other listeners to see. but it should be better.
