### ISSUE TITLE
have a command to switch a plugin or a group of plugins

### ISSUE THREAD

**Issue by Adriz1er** [1C0D/obsidian-quick-plugin-switcher#7]
It's in the title

**Comment by 1C0D** [comment]
You will have to be more specific. I really don't see what you are meaning. give me an example explaining step by step what you mean, by a command to switch plugin(s). what is switch? enable I guess (not install ?). you can enable a group of plugins right clicking on a group
![image](https://github.com/1C0D/obsidian-quick-plugin-switcher/assets/63018905/48b71542-f856-4049-ab33-86a6242797ad)

**Comment by Adriz1er** [comment]
Ok sorry I don't speak English well, I think a command to activate a particular plugin would be practical

**Comment by 1C0D** [comment]
I don't see how to do this. a command appearing in the command palette? it seems like a whole plugin to do

**Comment by Adriz1er** [comment]
It's ok I don't know also, I prefer talk about what I want because it's to pratice GTD method with obsidian

**Comment by 1C0D** [comment]
@Adriz1er 
version 7.2.0
I added this feature in the last version

**Comment by Adriz1er** [comment]
> @Adriz1er version 7.2.0 I added this feature in the last version

Thanks, it's for my template for obsidian vault, this is to prevent it from lagging. If you want you can have it on this link for free (but it's in french but it's not too impactful) : [template model](https://adrienromanoer.gumroad.com/l/tvift)

**Comment by Adriz1er** [comment]
@1C0D I think I asked you a bad thing because I think it's already exist or It's me because I haven't test. I hope you will sorry me.

**Comment by 1C0D** [comment]
I saw you are using a plugin to go full screen. I did a new plugin, it's called "editor full screen" (published). Very simple, but it's fixing major issues compared to what you were using.
