### ISSUE TITLE
FR: quick preview

### ISSUE THREAD

**Issue by gerroon** [1C0D/obsidian-quick-plugin-switcher#8]
Hi

It would be very nice if ctrl-mouse over could pull the plugin's submission or actual information page. The short info panel most of the does not show all the necessary info.

**Comment by 1C0D** [comment]
ok nice suggestion. description in the main modal should be more accurate now. it's was not updating well properties when changed. a quite big issue...

**Comment by 1C0D** [comment]
I didn't tell but ctrl is working now
