### ISSUE TITLE
FR: When the plugin is opened, the cursor is already in the search box

### ISSUE THREAD

**Issue by YIRU69** [1C0D/obsidian-quick-plugin-switcher#9]
Hello, I have been using your plugin to toggle other plugins on and off. I have been using it many times and found that the most frequent action for me is to search for a specific plugin. However, every time I have to click on the search box and move the mouse. So, I hope you can add a small function that when the plugin is opened, the cursor is already in the search box, so that I don't have to use the mouse.

**Comment by 1C0D** [comment]
In fact, the interface is restarting on every operation, as when pressing a shortcut. So having the focus on search on start can interfere with other focus, and they are so many situations possible that it's a mess to set. I tried, but it became overcomplicated very fast, for my level...

**Comment by 1C0D** [comment]
I finally did it

**Comment by YIRU69** [comment]
Thanks!
